name: Deploy to WordPress via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploying via SFTP
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: "/public_html/chiqnos.com/wp-content/themes/portfolio/"
          local-dir: "./portfolio_theme/"
          protocol: sftp
          port: ${{ secrets.SFTP_PORT }}
